name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Are you sure you want to destroy the infrastructure?"
        required: true
        type: choice
        options:
          - Keep
          - Destroy
        default: Keep

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm_destroy == 'Destroy' }}
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: devopseng4ai
      FUNCTION_NAME: devopseng4ai
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Destroy
        working-directory: terraform_infra
        run: |
          terraform init
          terraform destroy -auto-approve \
            -var="image_uri=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devopseng4ai:whatever" \
            -var="function_name=devopseng4ai"